package mario.worldofchemistry.datagen;

import mario.worldofchemistry.init.BlockInit;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class BlockLootTableProvider extends FabricBlockLootTableProvider {
    protected BlockLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(BlockInit.ELEMENT_0);
        addDrop(BlockInit.ELEMENT_1);
        addDrop(BlockInit.ELEMENT_2);
        addDrop(BlockInit.ELEMENT_3);
        addDrop(BlockInit.ELEMENT_4);
        addDrop(BlockInit.ELEMENT_5);
        addDrop(BlockInit.ELEMENT_6);
        addDrop(BlockInit.ELEMENT_7);
        addDrop(BlockInit.ELEMENT_8);
        addDrop(BlockInit.ELEMENT_9);
        addDrop(BlockInit.ELEMENT_10);
        addDrop(BlockInit.ELEMENT_11);
        addDrop(BlockInit.ELEMENT_12);
        addDrop(BlockInit.ELEMENT_13);
        addDrop(BlockInit.ELEMENT_14);
        addDrop(BlockInit.ELEMENT_15);
        addDrop(BlockInit.ELEMENT_16);
        addDrop(BlockInit.ELEMENT_17);
        addDrop(BlockInit.ELEMENT_18);
        addDrop(BlockInit.ELEMENT_19);
        addDrop(BlockInit.ELEMENT_20);
        addDrop(BlockInit.ELEMENT_21);
        addDrop(BlockInit.ELEMENT_22);
        addDrop(BlockInit.ELEMENT_23);
        addDrop(BlockInit.ELEMENT_24);
        addDrop(BlockInit.ELEMENT_25);
        addDrop(BlockInit.ELEMENT_26);
        addDrop(BlockInit.ELEMENT_27);
        addDrop(BlockInit.ELEMENT_28);
        addDrop(BlockInit.ELEMENT_29);
        addDrop(BlockInit.ELEMENT_30);
        addDrop(BlockInit.ELEMENT_31);
        addDrop(BlockInit.ELEMENT_32);
        addDrop(BlockInit.ELEMENT_33);
        addDrop(BlockInit.ELEMENT_34);
        addDrop(BlockInit.ELEMENT_35);
        addDrop(BlockInit.ELEMENT_36);
        addDrop(BlockInit.ELEMENT_37);
        addDrop(BlockInit.ELEMENT_38);
        addDrop(BlockInit.ELEMENT_39);
        addDrop(BlockInit.ELEMENT_40);
        addDrop(BlockInit.ELEMENT_41);
        addDrop(BlockInit.ELEMENT_42);
        addDrop(BlockInit.ELEMENT_43);
        addDrop(BlockInit.ELEMENT_44);
        addDrop(BlockInit.ELEMENT_45);
        addDrop(BlockInit.ELEMENT_46);
        addDrop(BlockInit.ELEMENT_47);
        addDrop(BlockInit.ELEMENT_48);
        addDrop(BlockInit.ELEMENT_49);
        addDrop(BlockInit.ELEMENT_50);
        addDrop(BlockInit.ELEMENT_51);
        addDrop(BlockInit.ELEMENT_52);
        addDrop(BlockInit.ELEMENT_53);
        addDrop(BlockInit.ELEMENT_54);
        addDrop(BlockInit.ELEMENT_55);
        addDrop(BlockInit.ELEMENT_56);
        addDrop(BlockInit.ELEMENT_57);
        addDrop(BlockInit.ELEMENT_58);
        addDrop(BlockInit.ELEMENT_59);
        addDrop(BlockInit.ELEMENT_60);
        addDrop(BlockInit.ELEMENT_61);
        addDrop(BlockInit.ELEMENT_62);
        addDrop(BlockInit.ELEMENT_63);
        addDrop(BlockInit.ELEMENT_64);
        addDrop(BlockInit.ELEMENT_65);
        addDrop(BlockInit.ELEMENT_66);
        addDrop(BlockInit.ELEMENT_67);
        addDrop(BlockInit.ELEMENT_68);
        addDrop(BlockInit.ELEMENT_69);
        addDrop(BlockInit.ELEMENT_70);
        addDrop(BlockInit.ELEMENT_71);
        addDrop(BlockInit.ELEMENT_72);
        addDrop(BlockInit.ELEMENT_73);
        addDrop(BlockInit.ELEMENT_74);
        addDrop(BlockInit.ELEMENT_75);
        addDrop(BlockInit.ELEMENT_76);
        addDrop(BlockInit.ELEMENT_77);
        addDrop(BlockInit.ELEMENT_78);
        addDrop(BlockInit.ELEMENT_79);
        addDrop(BlockInit.ELEMENT_80);
        addDrop(BlockInit.ELEMENT_81);
        addDrop(BlockInit.ELEMENT_82);
        addDrop(BlockInit.ELEMENT_83);
        addDrop(BlockInit.ELEMENT_84);
        addDrop(BlockInit.ELEMENT_85);
        addDrop(BlockInit.ELEMENT_86);
        addDrop(BlockInit.ELEMENT_87);
        addDrop(BlockInit.ELEMENT_88);
        addDrop(BlockInit.ELEMENT_89);
        addDrop(BlockInit.ELEMENT_90);
        addDrop(BlockInit.ELEMENT_91);
        addDrop(BlockInit.ELEMENT_92);
        addDrop(BlockInit.ELEMENT_93);
        addDrop(BlockInit.ELEMENT_94);
        addDrop(BlockInit.ELEMENT_95);
        addDrop(BlockInit.ELEMENT_96);
        addDrop(BlockInit.ELEMENT_97);
        addDrop(BlockInit.ELEMENT_98);
        addDrop(BlockInit.ELEMENT_99);
        addDrop(BlockInit.ELEMENT_100);
        addDrop(BlockInit.ELEMENT_101);
        addDrop(BlockInit.ELEMENT_102);
        addDrop(BlockInit.ELEMENT_103);
        addDrop(BlockInit.ELEMENT_104);
        addDrop(BlockInit.ELEMENT_105);
        addDrop(BlockInit.ELEMENT_106);
        addDrop(BlockInit.ELEMENT_107);
        addDrop(BlockInit.ELEMENT_108);
        addDrop(BlockInit.ELEMENT_109);
        addDrop(BlockInit.ELEMENT_110);
        addDrop(BlockInit.ELEMENT_111);
        addDrop(BlockInit.ELEMENT_112);
        addDrop(BlockInit.ELEMENT_113);
        addDrop(BlockInit.ELEMENT_114);
        addDrop(BlockInit.ELEMENT_115);
        addDrop(BlockInit.ELEMENT_116);
        addDrop(BlockInit.ELEMENT_117);
        addDrop(BlockInit.ELEMENT_118);
    }
}