package mario.worldofchemistry.datagen;

import mario.worldofchemistry.init.BlockInit;
import mario.worldofchemistry.init.ItemInit;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class EnglishUSLangProvider extends FabricLanguageProvider {
    protected EnglishUSLangProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        // Specifying en_us is optional, as it's the default language code
        super(dataOutput, "en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, FabricLanguageProvider.TranslationBuilder translationBuilder) {
        translationBuilder.add("itemGroup.woc", "World of Chemistry");
        translationBuilder.add(BlockInit.ELEMENT_0.asItem(), "???");
        translationBuilder.add(BlockInit.ELEMENT_1.asItem(), "Hydrogen");
        translationBuilder.add(BlockInit.ELEMENT_2.asItem(), "Helium");
        translationBuilder.add(BlockInit.ELEMENT_3.asItem(), "Lithium");
        translationBuilder.add(BlockInit.ELEMENT_4.asItem(), "Beryllium");
        translationBuilder.add(BlockInit.ELEMENT_5.asItem(), "Boron");
        translationBuilder.add(BlockInit.ELEMENT_6.asItem(), "Carbon");
        translationBuilder.add(BlockInit.ELEMENT_7.asItem(), "Nitrogen");
        translationBuilder.add(BlockInit.ELEMENT_8.asItem(), "Oxygen");
        translationBuilder.add(BlockInit.ELEMENT_9.asItem(), "Fluorine");
        translationBuilder.add(BlockInit.ELEMENT_10.asItem(), "Neon");
        translationBuilder.add(BlockInit.ELEMENT_11.asItem(), "Sodium");
        translationBuilder.add(BlockInit.ELEMENT_12.asItem(), "Magnesium");
        translationBuilder.add(BlockInit.ELEMENT_13.asItem(), "Aluminum");
        translationBuilder.add(BlockInit.ELEMENT_14.asItem(), "Silicon");
        translationBuilder.add(BlockInit.ELEMENT_15.asItem(), "Phosphorus");
        translationBuilder.add(BlockInit.ELEMENT_16.asItem(), "Sulfur");
        translationBuilder.add(BlockInit.ELEMENT_17.asItem(), "Chlorine");
        translationBuilder.add(BlockInit.ELEMENT_18.asItem(), "Argon");
        translationBuilder.add(BlockInit.ELEMENT_19.asItem(), "Potassium");
        translationBuilder.add(BlockInit.ELEMENT_20.asItem(), "Calcium");
        translationBuilder.add(BlockInit.ELEMENT_21.asItem(), "Scandium");
        translationBuilder.add(BlockInit.ELEMENT_22.asItem(), "Titanium");
        translationBuilder.add(BlockInit.ELEMENT_23.asItem(), "Vanadium");
        translationBuilder.add(BlockInit.ELEMENT_24.asItem(), "Chromium");
        translationBuilder.add(BlockInit.ELEMENT_25.asItem(), "Manganese");
        translationBuilder.add(BlockInit.ELEMENT_26.asItem(), "Iron");
        translationBuilder.add(BlockInit.ELEMENT_27.asItem(), "Cobalt");
        translationBuilder.add(BlockInit.ELEMENT_28.asItem(), "Nickel");
        translationBuilder.add(BlockInit.ELEMENT_29.asItem(), "Copper");
        translationBuilder.add(BlockInit.ELEMENT_30.asItem(), "Zinc");
        translationBuilder.add(BlockInit.ELEMENT_31.asItem(), "Gallium");
        translationBuilder.add(BlockInit.ELEMENT_32.asItem(), "Germanium");
        translationBuilder.add(BlockInit.ELEMENT_33.asItem(), "Arsenic");
        translationBuilder.add(BlockInit.ELEMENT_34.asItem(), "Selenium");
        translationBuilder.add(BlockInit.ELEMENT_35.asItem(), "Bromine");
        translationBuilder.add(BlockInit.ELEMENT_36.asItem(), "Krypton");
        translationBuilder.add(BlockInit.ELEMENT_37.asItem(), "Rubidium");
        translationBuilder.add(BlockInit.ELEMENT_38.asItem(), "Strontium");
        translationBuilder.add(BlockInit.ELEMENT_39.asItem(), "Yttrium");
        translationBuilder.add(BlockInit.ELEMENT_40.asItem(), "Zirconium");
        translationBuilder.add(BlockInit.ELEMENT_41.asItem(), "Niobium");
        translationBuilder.add(BlockInit.ELEMENT_42.asItem(), "Molybdenum");
        translationBuilder.add(BlockInit.ELEMENT_43.asItem(), "Technetium");
        translationBuilder.add(BlockInit.ELEMENT_44.asItem(), "Ruthenium");
        translationBuilder.add(BlockInit.ELEMENT_45.asItem(), "Rhodium");
        translationBuilder.add(BlockInit.ELEMENT_46.asItem(), "Palladium");
        translationBuilder.add(BlockInit.ELEMENT_47.asItem(), "Silver");
        translationBuilder.add(BlockInit.ELEMENT_48.asItem(), "Cadmium");
        translationBuilder.add(BlockInit.ELEMENT_49.asItem(), "Indium");
        translationBuilder.add(BlockInit.ELEMENT_50.asItem(), "Tin");
        translationBuilder.add(BlockInit.ELEMENT_51.asItem(), "Antimony");
        translationBuilder.add(BlockInit.ELEMENT_52.asItem(), "Tellurium");
        translationBuilder.add(BlockInit.ELEMENT_53.asItem(), "Iodine");
        translationBuilder.add(BlockInit.ELEMENT_54.asItem(), "Xenon");
        translationBuilder.add(BlockInit.ELEMENT_55.asItem(), "Cesium");
        translationBuilder.add(BlockInit.ELEMENT_56.asItem(), "Barium");
        translationBuilder.add(BlockInit.ELEMENT_57.asItem(), "Lanthanum");
        translationBuilder.add(BlockInit.ELEMENT_58.asItem(), "Cerium");
        translationBuilder.add(BlockInit.ELEMENT_59.asItem(), "Praseodymium");
        translationBuilder.add(BlockInit.ELEMENT_60.asItem(), "Neodymium");
        translationBuilder.add(BlockInit.ELEMENT_61.asItem(), "Promethium");
        translationBuilder.add(BlockInit.ELEMENT_62.asItem(), "Samarium");
        translationBuilder.add(BlockInit.ELEMENT_63.asItem(), "Europium");
        translationBuilder.add(BlockInit.ELEMENT_64.asItem(), "Gadolinium");
        translationBuilder.add(BlockInit.ELEMENT_65.asItem(), "Terbium");
        translationBuilder.add(BlockInit.ELEMENT_66.asItem(), "Dysprosium");
        translationBuilder.add(BlockInit.ELEMENT_67.asItem(), "Holmium");
        translationBuilder.add(BlockInit.ELEMENT_68.asItem(), "Erbium");
        translationBuilder.add(BlockInit.ELEMENT_69.asItem(), "Thulium");
        translationBuilder.add(BlockInit.ELEMENT_70.asItem(), "Ytterbium");
        translationBuilder.add(BlockInit.ELEMENT_71.asItem(), "Lutetium");
        translationBuilder.add(BlockInit.ELEMENT_72.asItem(), "Hafnium");
        translationBuilder.add(BlockInit.ELEMENT_73.asItem(), "Tantalum");
        translationBuilder.add(BlockInit.ELEMENT_74.asItem(), "Tungsten");
        translationBuilder.add(BlockInit.ELEMENT_75.asItem(), "Rhenium");
        translationBuilder.add(BlockInit.ELEMENT_76.asItem(), "Osmium");
        translationBuilder.add(BlockInit.ELEMENT_77.asItem(), "Iridium");
        translationBuilder.add(BlockInit.ELEMENT_78.asItem(), "Platinum");
        translationBuilder.add(BlockInit.ELEMENT_79.asItem(), "Gold");
        translationBuilder.add(BlockInit.ELEMENT_80.asItem(), "Mercury");
        translationBuilder.add(BlockInit.ELEMENT_81.asItem(), "Thallium");
        translationBuilder.add(BlockInit.ELEMENT_82.asItem(), "Lead");
        translationBuilder.add(BlockInit.ELEMENT_83.asItem(), "Bismuth");
        translationBuilder.add(BlockInit.ELEMENT_84.asItem(), "Polonium");
        translationBuilder.add(BlockInit.ELEMENT_85.asItem(), "Astatine");
        translationBuilder.add(BlockInit.ELEMENT_86.asItem(), "Radon");
        translationBuilder.add(BlockInit.ELEMENT_87.asItem(), "Francium");
        translationBuilder.add(BlockInit.ELEMENT_88.asItem(), "Radium");
        translationBuilder.add(BlockInit.ELEMENT_89.asItem(), "Actinium");
        translationBuilder.add(BlockInit.ELEMENT_90.asItem(), "Thorium");
        translationBuilder.add(BlockInit.ELEMENT_91.asItem(), "Protactinium");
        translationBuilder.add(BlockInit.ELEMENT_92.asItem(), "Uranium");
        translationBuilder.add(BlockInit.ELEMENT_93.asItem(), "Neptunium");
        translationBuilder.add(BlockInit.ELEMENT_94.asItem(), "Plutonium");
        translationBuilder.add(BlockInit.ELEMENT_95.asItem(), "Americium");
        translationBuilder.add(BlockInit.ELEMENT_96.asItem(), "Curium");
        translationBuilder.add(BlockInit.ELEMENT_97.asItem(), "Berkelium");
        translationBuilder.add(BlockInit.ELEMENT_98.asItem(), "Californium");
        translationBuilder.add(BlockInit.ELEMENT_99.asItem(), "Einsteinium");
        translationBuilder.add(BlockInit.ELEMENT_100.asItem(), "Fermium");
        translationBuilder.add(BlockInit.ELEMENT_101.asItem(), "Mendelevium");
        translationBuilder.add(BlockInit.ELEMENT_102.asItem(), "Nobelium");
        translationBuilder.add(BlockInit.ELEMENT_103.asItem(), "Lawrencium");
        translationBuilder.add(BlockInit.ELEMENT_104.asItem(), "Rutherfordium");
        translationBuilder.add(BlockInit.ELEMENT_105.asItem(), "Dubnium");
        translationBuilder.add(BlockInit.ELEMENT_106.asItem(), "Seaborgium");
        translationBuilder.add(BlockInit.ELEMENT_107.asItem(), "Bohrium");
        translationBuilder.add(BlockInit.ELEMENT_108.asItem(), "Hassium");
        translationBuilder.add(BlockInit.ELEMENT_109.asItem(), "Meitnerium");
        translationBuilder.add(BlockInit.ELEMENT_110.asItem(), "Darmstadtium");
        translationBuilder.add(BlockInit.ELEMENT_111.asItem(), "Roentgenium");
        translationBuilder.add(BlockInit.ELEMENT_112.asItem(), "Copernicium");
        translationBuilder.add(BlockInit.ELEMENT_113.asItem(), "Nihonium");
        translationBuilder.add(BlockInit.ELEMENT_114.asItem(), "Flerovium");
        translationBuilder.add(BlockInit.ELEMENT_115.asItem(), "Moscovium");
        translationBuilder.add(BlockInit.ELEMENT_116.asItem(), "Livermorium");
        translationBuilder.add(BlockInit.ELEMENT_117.asItem(), "Tennessine");
        translationBuilder.add(BlockInit.ELEMENT_118.asItem(), "Oganesson");
        translationBuilder.add(BlockInit.ELEMENT_CONSTRUCTOR, "Element Constructor");
        translationBuilder.add(BlockInit.ELEMENT_CONSTRUCTOR.asItem(), "Element Constructor");
        translationBuilder.add(ItemInit.SALT, "Salt");
        translationBuilder.add(ItemInit.SODIUM_OXIDE, "Sodium Oxide");
        translationBuilder.add(ItemInit.SODIUM_HYDROXIDE, "Lye");
        translationBuilder.add(ItemInit.MAGNESIUM_NITRATE, "Magnesium Nitrate");
        translationBuilder.add(ItemInit.IRON_SULFIDE, "Iron Sulfide");
        translationBuilder.add(ItemInit.LITHIUM_HYDRIDE, "Lithium Hydride");
        translationBuilder.add(ItemInit.SODIUM_HYDRIDE, "Sodium Hydride");
        translationBuilder.add(ItemInit.CALCIUM_BROMIDE, "Calcium Bromide");
        translationBuilder.add(ItemInit.MAGNESIUM_OXIDE, "Magnesium Oxide");
        translationBuilder.add(ItemInit.SODIUM_ACETATE, "Sodium Acetate");
        translationBuilder.add(ItemInit.LUMINOL, "Luminol");
        translationBuilder.add(ItemInit.ALUMINUM_OXIDE, "Aluminum Oxide");
        translationBuilder.add(ItemInit.BORON_TRIOXIDE, "Boron Trioxide");
        translationBuilder.add(ItemInit.SOAP, "Soap");
        translationBuilder.add(ItemInit.POLYETHYLENE, "Polyethylene");
        translationBuilder.add(ItemInit.GARBAGE, "Garbage");
        translationBuilder.add(ItemInit.MAGNESIUM_SALTS, "Magnesium Salts");
        translationBuilder.add(ItemInit.SULFATE, "Sulfate");
        translationBuilder.add(ItemInit.BARIUM_SULFATE, "Barium Sulfate");
        translationBuilder.add(ItemInit.POTASSIUM_CHLORIDE, "Potassium Chloride");
        translationBuilder.add(ItemInit.MERCURIC_CHLORIDE, "Mercuric Chloride");
        translationBuilder.add(ItemInit.CERIUM_CHLORIDE, "Cerium Chloride");
        translationBuilder.add(ItemInit.TUNGSTEN_CHLORIDE, "Tungsten Chloride");
        translationBuilder.add(ItemInit.CALCIUM_CHLORIDE, "Calcium Chloride");
        translationBuilder.add(ItemInit.WATER, "Water");
        translationBuilder.add(ItemInit.GLUE, "Glue");
        translationBuilder.add(ItemInit.HYPOCHLORITE, "Hypochlorite");
        translationBuilder.add(ItemInit.CRUDE_OIL, "Crude Oil");
        translationBuilder.add(ItemInit.LATEX, "Latex");
        translationBuilder.add(ItemInit.POTASSIUM_IODIDE, "Potassium Iodide");
        translationBuilder.add(ItemInit.SODIUM_FLUORIDE, "Sodium Fluoride");
        translationBuilder.add(ItemInit.BENZENE, "Benzene");
        translationBuilder.add(ItemInit.HYDROGEN_PEROXIDE, "Hydrogen Peroxide");
        translationBuilder.add(ItemInit.AMMONIA, "Ammonia");
        translationBuilder.add(ItemInit.SODIUM_HYPOCHLORITE, "Sodium Hypochlorite");
        translationBuilder.add(ItemInit.RAPID_FERTILIZER, "Super Fertilizer");
        translationBuilder.add(ItemInit.ICE_BOMB, "Ice Bomb");
        translationBuilder.add(ItemInit.BLEACH, "Bleach");
    }
}
