# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w20a
yarn_mappings=25w20a+build.4
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=mario.worldofchemistry
archives_base_name=worldofchemistry

# Dependencies
fabric_version=0.124.1+1.21.6