package mario3264.mod.init;

import java.util.ArrayList;
import java.util.List;

import mario3264.mod.objects.blocks.BlockBase;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;

public class BlockInit 
{
	public static final List<Block> BLOCKS = new ArrayList<Block>();
	
	public static final Block ELEMENT_0 = new BlockBase("element_0", Material.ROCK);
	public static final Block ELEMENT_1 = new BlockBase("element_1", Material.ROCK);
	public static final Block ELEMENT_2 = new BlockBase("element_2", Material.ROCK);
	public static final Block ELEMENT_3 = new BlockBase("element_3", Material.ROCK);
	public static final Block ELEMENT_4 = new BlockBase("element_4", Material.ROCK);
	public static final Block ELEMENT_5 = new BlockBase("element_5", Material.ROCK);
	public static final Block ELEMENT_6 = new BlockBase("element_6", Material.ROCK);
	public static final Block ELEMENT_7 = new BlockBase("element_7", Material.ROCK);
	public static final Block ELEMENT_8 = new BlockBase("element_8", Material.ROCK);
	public static final Block ELEMENT_9 = new BlockBase("element_9", Material.ROCK);
	public static final Block ELEMENT_10 = new BlockBase("element_10", Material.ROCK);
	public static final Block ELEMENT_11 = new BlockBase("element_11", Material.ROCK);
	public static final Block ELEMENT_12 = new BlockBase("element_12", Material.ROCK);
	public static final Block ELEMENT_13 = new BlockBase("element_13", Material.ROCK);
	public static final Block ELEMENT_14 = new BlockBase("element_14", Material.ROCK);
	public static final Block ELEMENT_15 = new BlockBase("element_15", Material.ROCK);
	public static final Block ELEMENT_16 = new BlockBase("element_16", Material.ROCK);
	public static final Block ELEMENT_17 = new BlockBase("element_17", Material.ROCK);
	public static final Block ELEMENT_18 = new BlockBase("element_18", Material.ROCK);
	public static final Block ELEMENT_19 = new BlockBase("element_19", Material.ROCK);
	public static final Block ELEMENT_20 = new BlockBase("element_20", Material.ROCK);
	public static final Block ELEMENT_21 = new BlockBase("element_21", Material.ROCK);
	public static final Block ELEMENT_22 = new BlockBase("element_22", Material.ROCK);
	public static final Block ELEMENT_23 = new BlockBase("element_23", Material.ROCK);
	public static final Block ELEMENT_24 = new BlockBase("element_24", Material.ROCK);
	public static final Block ELEMENT_25 = new BlockBase("element_25", Material.ROCK);
	public static final Block ELEMENT_26 = new BlockBase("element_26", Material.ROCK);
	public static final Block ELEMENT_27 = new BlockBase("element_27", Material.ROCK);
	public static final Block ELEMENT_28 = new BlockBase("element_28", Material.ROCK);
	public static final Block ELEMENT_29 = new BlockBase("element_29", Material.ROCK);
	public static final Block ELEMENT_30 = new BlockBase("element_30", Material.ROCK);
	public static final Block ELEMENT_31 = new BlockBase("element_31", Material.ROCK);
	public static final Block ELEMENT_32 = new BlockBase("element_32", Material.ROCK);
	public static final Block ELEMENT_33 = new BlockBase("element_33", Material.ROCK);
	public static final Block ELEMENT_34 = new BlockBase("element_34", Material.ROCK);
	public static final Block ELEMENT_35 = new BlockBase("element_35", Material.ROCK);
	public static final Block ELEMENT_36 = new BlockBase("element_36", Material.ROCK);
	public static final Block ELEMENT_37 = new BlockBase("element_37", Material.ROCK);
	public static final Block ELEMENT_38 = new BlockBase("element_38", Material.ROCK);
	public static final Block ELEMENT_39 = new BlockBase("element_39", Material.ROCK);
	public static final Block ELEMENT_40 = new BlockBase("element_40", Material.ROCK);
	public static final Block ELEMENT_41 = new BlockBase("element_41", Material.ROCK);
	public static final Block ELEMENT_42 = new BlockBase("element_42", Material.ROCK);
	public static final Block ELEMENT_43 = new BlockBase("element_43", Material.ROCK);
	public static final Block ELEMENT_44 = new BlockBase("element_44", Material.ROCK);
	public static final Block ELEMENT_45 = new BlockBase("element_45", Material.ROCK);
	public static final Block ELEMENT_46 = new BlockBase("element_46", Material.ROCK);
	public static final Block ELEMENT_47 = new BlockBase("element_47", Material.ROCK);
	public static final Block ELEMENT_48 = new BlockBase("element_48", Material.ROCK);
	public static final Block ELEMENT_49 = new BlockBase("element_49", Material.ROCK);
	public static final Block ELEMENT_50 = new BlockBase("element_50", Material.ROCK);
	public static final Block ELEMENT_51 = new BlockBase("element_51", Material.ROCK);
	public static final Block ELEMENT_52 = new BlockBase("element_52", Material.ROCK);
	public static final Block ELEMENT_53 = new BlockBase("element_53", Material.ROCK);
	public static final Block ELEMENT_54 = new BlockBase("element_54", Material.ROCK);
	public static final Block ELEMENT_55 = new BlockBase("element_55", Material.ROCK);
	public static final Block ELEMENT_56 = new BlockBase("element_56", Material.ROCK);
	public static final Block ELEMENT_57 = new BlockBase("element_57", Material.ROCK);
	public static final Block ELEMENT_58 = new BlockBase("element_58", Material.ROCK);
	public static final Block ELEMENT_59 = new BlockBase("element_59", Material.ROCK);
	public static final Block ELEMENT_60 = new BlockBase("element_60", Material.ROCK);
	public static final Block ELEMENT_61 = new BlockBase("element_61", Material.ROCK);
	public static final Block ELEMENT_62 = new BlockBase("element_62", Material.ROCK);
	public static final Block ELEMENT_63 = new BlockBase("element_63", Material.ROCK);
	public static final Block ELEMENT_64 = new BlockBase("element_64", Material.ROCK);
	public static final Block ELEMENT_65 = new BlockBase("element_65", Material.ROCK);
	public static final Block ELEMENT_66 = new BlockBase("element_66", Material.ROCK);
	public static final Block ELEMENT_67 = new BlockBase("element_67", Material.ROCK);
	public static final Block ELEMENT_68 = new BlockBase("element_68", Material.ROCK);
	public static final Block ELEMENT_69 = new BlockBase("element_69", Material.ROCK);
	public static final Block ELEMENT_70 = new BlockBase("element_70", Material.ROCK);
	public static final Block ELEMENT_71 = new BlockBase("element_71", Material.ROCK);
	public static final Block ELEMENT_72 = new BlockBase("element_72", Material.ROCK);
	public static final Block ELEMENT_73 = new BlockBase("element_73", Material.ROCK);
	public static final Block ELEMENT_74 = new BlockBase("element_74", Material.ROCK);
	public static final Block ELEMENT_75 = new BlockBase("element_75", Material.ROCK);
	public static final Block ELEMENT_76 = new BlockBase("element_76", Material.ROCK);
	public static final Block ELEMENT_77 = new BlockBase("element_77", Material.ROCK);
	public static final Block ELEMENT_78 = new BlockBase("element_78", Material.ROCK);
	public static final Block ELEMENT_79 = new BlockBase("element_79", Material.ROCK);
	public static final Block ELEMENT_80 = new BlockBase("element_80", Material.ROCK);
	public static final Block ELEMENT_81 = new BlockBase("element_81", Material.ROCK);
	public static final Block ELEMENT_82 = new BlockBase("element_82", Material.ROCK);
	public static final Block ELEMENT_83 = new BlockBase("element_83", Material.ROCK);
}
